### ISSUE TITLE
Template untuk heading chapter kurang ke kanan

### ISSUE THREAD

**Issue by fushar** [ia-toki/training-gate-id-book#2]
Content-nya jadi bleber gitu:

![screenshot 2017-11-05 10 59 11](https://user-images.githubusercontent.com/1525580/32411863-c3657b74-c218-11e7-9286-0583762a2994.png)

**Comment by sokokaleb** [comment]
Ini somehow ada yang edit template book awalnya deh... will be resolved in #20.

**Comment by sokokaleb** [comment]
Resolved by #20.
