### ISSUE TITLE
\subsubsection error

### ISSUE THREAD

**Issue by fairuzi10** [ia-toki/training-gate-id-book#23]
pada texlive-full di ubuntu 16.04, entah mengapa \subsubsection error padahal jika digunakan di file .tex lain tidak ada masalah. Mungkin karena package? :/

![saat compile](https://user-images.githubusercontent.com/26700337/32928418-641cdbf6-cb84-11e7-9c19-5a4def4ac5fa.jpg)

perbandingan antara yang bermasalah dengan yang seharusnya

![saat dilihat](https://user-images.githubusercontent.com/26700337/32928417-63dd240c-cb84-11e7-9871-57f609553c3d.jpg)

**Comment by ilhamwk** [comment]
Itu karena gak ada definisi \titleformat buat subsubsection. Sending a fix.
