### ISSUE TITLE
Bersihin main.tex

### ISSUE THREAD

**Issue by ilhamwk** [ia-toki/training-gate-id-book#28]
Baca kode LaTeX-nya pusing. Ditambah lagi main.tex penuh komentar dalam Bahasa Catalan (ada yang ngerti?).

**Comment by ilhamwk** [comment]
Ada yang ngerti kenapa segitu banyak paket ditambahin? Apa semuanya dibutuhin?

**Comment by sokokaleb** [comment]
Kayaknya karena base pengerjaannya pakai suatu template `gnu_book` gitu. @afaji might know better :')

**Comment by afaji** [comment]
karena itu pakai template. Konten langsung di folder topik/ aja. Template masih bisa berubah2 juga, hence main.tex mungkin bisa ganti juga.

**Comment by afaji** [comment]
Kalo ada rekomendasi template buku latex yang bagus, feel free to point us. pertimbangannya: desainnnya bikin enak dibaca, dan lisensinya jelas. So far adanya cuman ini.
