### ISSUE TITLE
\proc belum ada stylingnya

### ISSUE THREAD

**Issue by fushar** [ia-toki/training-gate-id-book#3]
Sekarang masih terlihat sama dengan tanpa `\proc`

**Comment by sokokaleb** [comment]
Ini tuh sebenernya ada, tapi kayaknya di-override sama template yang kita pake (maybe terkait setingan fontstyle/family), which I ain't have time buat cari tau templatenya ini ngedit apa aja (well, butuh waktu banyak soalnya 😂 ).

Will look later ya, P2.

**Comment by gyosh** [comment]
penyebabnya karena font "bera" yg dipakai gak ada style buat small caps, yg mana dipakai di \proc

**Comment by gyosh** [comment]
Muncul lagi masalah ini
