### ISSUE TITLE
[ht!] masih ga mempan buat ngefixin posisi gambar

### ISSUE THREAD

**Issue by cakraww** [ia-toki/training-gate-id-book#8]
![selection_007](https://user-images.githubusercontent.com/4298417/32412521-abf71f56-c22c-11e7-8de7-f58d88b257de.jpg)

gimana caranya supaya konten setelah image (text, paragraf, dll) di .tex nya ga muncul setelah image setelah di-compile?

**Comment by alijaya** [comment]
[H] ?

**Comment by alijaya** [comment]
atau... di shuffle aja... taro di seblom text yang lain

**Comment by sokokaleb** [comment]
Somehow `[H]` bikin the file (`main.tex`) compiles tapi ga bisa dibuka (crash di gw, lemot banget). Maybe `[H]` dari package `float` does something nasty other than setting the float setting...

**Comment by alijaya** [comment]
Better ganti urutan aja sih :-?... taro gambarnya setelah heading... :D

**Comment by sokokaleb** [comment]
Ini maksudnya Cakra bukan

"gimana caranya supaya konten setelah image (text, paragraf, dll) di .tex nya ga muncul setelah image setelah di-compile?"

tapi

"gimana caranya supaya konten setelah image muncul as is di code LaTeX-nya?"

gak sih. Bener gak? @cakraww

**Comment by cakraww** [comment]
sori iya harusnya gw nulisnya
gimana caranya supaya konten **yang ditaruh sebelum** image (text, paragraf, dll) di .tex nya ga muncul setelah image setelah di-compile?
